# Generated by Django 2.0 on 2018-12-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_name', models.CharField(max_length=1024)),
                ('track_id', models.IntegerField(primary_key=True, serialize=False)),
                ('added', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=1500)),
            ],
        ),
    ]
